/**
 * @file db.h
 * @brief High-level wrapper for SQLite3 database operations.
 *
 * Provides a simplified interface for executing SQL queries and iterating
 * result sets via a cursor. Parameter binding is driven by a compact
 * format string — one character per placeholder:
 *
 *   's' : const char *  (string)
 *   'i' : int
 *   'l' : int64_t
 *   'f' : double
 *   'n' : NULL
 */

#ifndef DB_H
#define DB_H

#include <stdint.h>
#include <stdbool.h>
#include <sqlite3.h>
#include "config.h"

/**
 * @brief Opens (or creates) a SQLite database at the given path.
 *
 * Applies WAL journal mode, NORMAL synchronous level and an 8 MB page
 * cache to the connection before returning.
 *
 * @pre path points to a writable filesystem location.
 * @post On success a global connection is established and ready for use.
 * @param path Path to the .db file.
 * @return 0 on success, -1 if the database cannot be opened.
 */
int db_init(const char *path);

/**
 * @brief Closes the global database connection.
 * @post The handle is set to NULL; further queries will fail safely.
 */
void db_close(void);

/**
 * @brief Returns the last SQLite error message.
 * @return Human-readable error string, or "no db" if not initialised.
 */
const char *db_errmsg(void);

/**
 * @brief Returns the rowid generated by the most recent INSERT.
 * @return 64-bit rowid, or 0 if no connection is open.
 */
int64_t db_last_insert_id(void);

/**
 * @brief Returns the number of rows affected by the last DML statement.
 * @return Row count, or 0 if no connection is open.
 */
int db_changes(void);

/* ── Cursor API (SELECT) ─────────────────────────────────────────────── */

/**
 * @brief Opaque handle to an active result-set cursor.
 */
typedef struct DbCursor DbCursor;

/**
 * @brief Prepares and executes a SELECT query, returning an iterable cursor.
 *
 * @pre The database is initialised.
 * @pre The number of '?' placeholders in sql equals strlen(fmt).
 * @param sql Null-terminated SQL SELECT statement.
 * @param fmt Format string describing the bound parameters (may be NULL).
 * @param ... Arguments matching fmt, in order.
 * @return Pointer to a DbCursor on success, NULL on preparation error.
 */
DbCursor *db_cursor_open(const char *sql, const char *fmt, ...);

/**
 * @brief Advances the cursor to the next row.
 * @param cursor Pointer to the cursor.
 * @return true if a row is available, false at EOF or on error.
 */
bool db_cursor_next(DbCursor *cursor);

/**
 * @brief Reads a text value from the current row.
 *
 * @param cursor Pointer to the cursor.
 * @param col Zero-based column index.
 * @return Column value as a C string, or "" if NULL or cursor invalid.
 */
const char *db_cursor_text(DbCursor *cursor, int col);

/**
 * @brief Reads a 64-bit integer value from the current row.
 *
 * @param cursor Pointer to the cursor.
 * @param col Zero-based column index.
 * @return Column value, or 0 if NULL or cursor invalid.
 */
int64_t db_cursor_int64(DbCursor *cursor, int col);

/**
 * @brief Reads a double-precision float value from the current row.
 *
 * @param cursor Pointer to the cursor.
 * @param col Zero-based column index.
 * @return Column value, or 0.0 if NULL or cursor invalid.
 */
double db_cursor_double(DbCursor *cursor, int col);

/**
 * @brief Finalises the statement and frees the cursor.
 * @post cursor is invalid after this call.
 * @param cursor Pointer to the cursor to close.
 */
void db_cursor_close(DbCursor *cursor);

/* ── Execution API (INSERT / UPDATE / DELETE) ────────────────────────── */

/**
 * @brief Prepares and executes a non-query SQL statement.
 *
 * Expects SQLITE_DONE on completion. Suitable for INSERT, UPDATE, DELETE
 * and DDL statements (CREATE TABLE, etc.).
 *
 * @pre The database is initialised.
 * @pre The number of '?' placeholders in sql equals strlen(fmt).
 * @param sql Null-terminated SQL statement.
 * @param fmt Format string for bound parameters (may be NULL).
 * @param ... Arguments matching fmt, in order.
 * @return 0 on success, -1 on preparation or execution error.
 */
int db_exec(const char *sql, const char *fmt, ...);

#endif /* DB_H */